// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kquefhpkyyjxooonmcbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdWVmaHBreXlqeG9vb25tY2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTkyMDgsImV4cCI6MjA2NjA5NTIwOH0.O1o17sMbI4Ac8DL5fV9a9ls2TB8MXdpcUcFG23Yul6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);